package io.github.skriptinsight.utils.dsl.textmate.model

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonPropertyOrder
import com.fasterxml.jackson.databind.SerializationFeature
import com.fasterxml.jackson.databind.module.SimpleModule
import com.fasterxml.jackson.databind.ser.std.UUIDSerializer
import com.fasterxml.jackson.module.kotlin.jsonMapper
import io.github.skriptinsight.utils.dsl.textmate.annotations.LanguageDslMarker
import io.github.skriptinsight.utils.dsl.textmate.utils.RegexSerializer
import java.io.File
import java.util.*

@JsonPropertyOrder("__textmate_dsl_disclaimer", alphabetic = true)
@LanguageDslMarker
class TextMateLanguage : PatternContainer {
    @JsonProperty("__textmate_dsl_disclaimer")
    val disclaimer = arrayOf(
        "DO NOT MODIFY MANUALLY!",
        "This file has been auto-generated by the SkriptInsight TextMate DSL.",
    )

    var name: String? = null
    var scopeName: String? = null
    var uuid: UUID? = null
    val repository = mutableMapOf<String, TextMateRule>()
    override val patterns = mutableListOf<TextMateRule>()
    override val captures: MutableMap<String, TextMateRule> = mutableMapOf()

    override operator fun TextMateRule.unaryPlus(): TextMateRule {
        this@TextMateLanguage.repository[this.internalName] = this
        return this
    }

    fun dump(file: File) {
        jsonMapper {
            serializationInclusion(JsonInclude.Include.NON_EMPTY)
            this.addModule(SimpleModule().apply {
                addSerializer(UUID::class.java, UUIDSerializer())
                addSerializer(Regex::class.java, RegexSerializer)
            })
            enable(SerializationFeature.INDENT_OUTPUT)
        }.writeValue(file, this)
    }

}